version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: desafio-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: