FROM node:20-bullseye AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
#para gerar o Prisma Client
COPY prisma ./prisma
RUN npx prisma generate
COPY . .
RUN npm run build
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/prisma ./prisma
RUN npm install --omit=dev --legacy-peer-deps
COPY --from=builder /app/dist ./dist
#porta que o Render vai usar
EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]